const js = require("@eslint/js");
const globals = require("globals");
const jsdoc = require("eslint-plugin-jsdoc");
const tsdoc = require("eslint-plugin-tsdoc");
const tseslint = require("@typescript-eslint/eslint-plugin");
const tsParser = require("@typescript-eslint/parser");
const nextCoreWebVitals = require("eslint-config-next/core-web-vitals");
const drizzle = require("eslint-plugin-drizzle");

const REGISTRY_COMPONENT_FILES = [
  // shadcn/ui (common locations)
  "**/components/ui/**/*.{ts,tsx}",
  "**/app/components/ui/**/*.{ts,tsx}",

  // Vercel AI Elements (common locations)
  "**/components/ai-elements/**/*.{ts,tsx}",
  "**/app/components/ai-elements/**/*.{ts,tsx}",
];

module.exports = [
  {
    ignores: [
      ".next/**",
      "coverage/**",
      "dist/**",
      "node_modules/**",
      "out/**",
      "opensrc/**",
      ".next-docs/**",
      ".agents/**",
      // Generated by the Workflow DevKit bundler / manifest generator.
      "src/app/.well-known/workflow/**",
    ],
  },

  js.configs.recommended,

  // Next.js core rules (core-web-vitals) via flat config export.
  ...nextCoreWebVitals,

  {
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
      },
      parser: tsParser,
      parserOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
      },
    },
    plugins: {
      "@typescript-eslint": tseslint,
      drizzle,
      jsdoc,
      tsdoc,
    },
    rules: {
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "drizzle/enforce-delete-with-where": [
        "error",
        { drizzleObjectName: ["db", "tx"] },
      ],
      "drizzle/enforce-update-with-where": [
        "error",
        { drizzleObjectName: ["db", "tx"] },
      ],
      "jsdoc/check-alignment": "error",
      "jsdoc/check-param-names": "error",
      "jsdoc/require-description": "warn",

      // Require docs on exported APIs (warn to keep iteration fast).
      "jsdoc/require-jsdoc": [
        "error",
        {
          publicOnly: true,
          require: {
            ArrowFunctionExpression: true,
            ClassDeclaration: true,
            ClassExpression: true,
            FunctionDeclaration: true,
            FunctionExpression: true,
            MethodDefinition: true,
          },
        },
      ],
      "jsdoc/require-param": "error",
      "jsdoc/require-returns": "error",
      "jsdoc/tag-lines": ["error", "any", { startLines: 1 }],

      // Prefer the TypeScript-aware variant (with underscore ignore patterns).
      "no-unused-vars": "off",

      // TSDoc syntax enforcement
      "tsdoc/syntax": "error",
    },
    settings: {
      jsdoc: {
        mode: "typescript",
      },
    },
  },
  // Registry-installed components (shadcn/ui + AI Elements):
  // Keep linting and type-checking for correctness, but disable doc-enforcement rules
  // that are usually too noisy for generated/copied component templates.
  {
    files: REGISTRY_COMPONENT_FILES,
    rules: {
      "jsdoc/check-alignment": "off",
      "jsdoc/check-param-names": "off",
      "jsdoc/require-description": "off",
      "jsdoc/require-jsdoc": "off",
      "jsdoc/require-param": "off",
      "jsdoc/require-returns": "off",
      "jsdoc/tag-lines": "off",
      "tsdoc/syntax": "off",
    },
  },
];
