name: CI Setup
description: "Shared CI setup: Bun + dependency install (requires checkout)"

inputs:
  bun-version:
    description: "Bun version to install (default: 1.3.7)"
    required: false
    default: "1.3.7"

runs:
  using: composite
  steps:
    - name: Cache apt packages
      id: apt-cache
      uses: actions/cache@v5.0.3
      with:
        path: |
          /var/cache/apt/archives
          /var/lib/apt/lists
        key: apt-${{ runner.os }}-build-essential-python3

    - name: Install build tools (argon2)
      if: steps.apt-cache.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3
      shell: bash

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2.1.2
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: Cache Bun install
      uses: actions/cache@v5.0.3
      with:
        path: |
          ~/.bun/install/cache
        key: bun-${{ runner.os }}-${{ inputs.bun-version }}-${{ hashFiles('bun.lock') }}
        restore-keys: |
          bun-${{ runner.os }}-${{ inputs.bun-version }}-
          bun-${{ runner.os }}-

    - name: Install dependencies
      run: bun install --frozen-lockfile
      shell: bash
